services:
  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    command: node server.mjs
  
  front:
    build:
      context: ./front
    ports:
      - "3001:3001"
    volumes:
      - ./front:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev
  
  turnserver:
    build:
      context: ./turnserver
    ports:
      - "3478:3478"
      - "3478:3478/udp"
      - "5349:5349"
      - "5349:5349/udp"
    volumes:
      - ./turnserver/turnserver.conf:/etc/turnserver.conf
    command: ["turnserver", "-c", "/etc/turnserver.conf", "--log-file=/var/log/turnserver/turnserver.log", "--lt-cred-mech"]
